# Generated by Django 3.0.2 on 2020-02-01 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0002_auto_20200201_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='deskinstance',
            name='building',
            field=models.ForeignKey(help_text='Select a building for this desk instance', null=True, on_delete=django.db.models.deletion.SET_NULL, to='availability.Building'),
        ),
        migrations.AlterField(
            model_name='desk',
            name='building',
            field=models.ManyToManyField(help_text='Select a building for this desk', to='availability.Building'),
        ),
    ]
